## (Generalized) Cross Product

In n-D, a vector  perpendicular to n-1 vectors is given in (pseudo-)notation 
by 

$$
\star\left(\mathbf{r}_{1},\mathbf{r}_{2},\ldots,\mathbf{r}_{n-1}\right)=
\begin{vmatrix}\mathbf{e}_{1} & \mathbf{e}_{2} & \cdots & \mathbf{e}_{n}\\
x_{11} & x_{12} &  & x_{1n}\\
x_{21} & x_{22} &  & x_{2n}\\
\vdots &  & \ddots\\
x_{n-1,1} & x_{n-1,2} &  & x_{n-1,n}
\end{vmatrix}
$$

e.g. in 2D

$$
\begin{vmatrix}\mathbf{e}_{1} & \mathbf{e}_{2}\\
x & y
\end{vmatrix}=y\mathbf{e}_{1}-x\mathbf{e}_{2}
$$
and 3D

$$
\begin{eqnarray*}
\begin{vmatrix}\mathbf{e}_{1} & \mathbf{e}_{2} & \mathbf{e}_{3}\\
x_{1} & y_{1} & z_{1}\\
x_{2} & y_{2} & z_{2}
\end{vmatrix} & = & \mathbf{e}_{1}\begin{vmatrix}y_{1} & z_{1}\\
y_{2} & z_{2}
\end{vmatrix}-e_{2}\begin{vmatrix}x_{1} & z_{1}\\
x_{2} & z_{2}
\end{vmatrix}+e_{3}\begin{vmatrix}x_{1} & y_{1}\\
x_{2} & y_{2}
\end{vmatrix}\\
 & = & \mathbf{e}_{1}\left(y_{1}z_{2}-z_{1}y_{2}\right)-\mathbf{e}_{2}\left(x_{1}z_{2}-x_{2}z_{1}\right)+\mathbf{e}_{3}\left(x_{1}y_{2}-x_{2}y_{1}\right)
\end{eqnarray*}
$$

**Q1: Implement a function to compute (generalized) cross product for given $n-1$ vectors in $R^n$** (use `numpy.linalg.det` )



In [2]:
def CrossNd(V):
    """
    PRE:
        - V is a numpy.array of dimension (n,n-1)
    POST:
        - result is a numpy.array of dimension (n,), orthogonal to all columns of V
    """
    pass

In [24]:
def CrossNd(r):
    pass

## test case #1 : 2D

In [25]:
v1 = numpy.array([1., 2.])
v2 = numpy.array([3., 1.])
V = numpy.stack([v1,v2])
v1,v2,V

(array([1., 2.]),
 array([3., 1.]),
 array([[1., 2.],
        [3., 1.]]))

In [28]:
v1o = CrossNd((v1,))
v2o = CrossNd((v2,))
v1o,v2o

(array([ 2., -1.]), array([ 1., -3.]))

In [29]:
v1 @ v1o, v2 @ v2o

(0.0, -4.440892098500626e-16)

In [35]:
assert numpy.abs(v1 @ v1o)<1e-6
assert numpy.abs(v2 @ v2o)<1e-6

## test case #2 : 3D

---
input vectors

In [36]:
v1 = numpy.array([3.,  1., 0.5])
v2 = numpy.array([0.3, 4., 0.2])
v3 = numpy.array([0.,  0.4, 2.5])
V = numpy.stack([v1,v2,v3])
v1,v2,v3,V

(array([3. , 1. , 0.5]),
 array([0.3, 4. , 0.2]),
 array([0. , 0.4, 2.5]),
 array([[3. , 1. , 0.5],
        [0.3, 4. , 0.2],
        [0. , 0.4, 2.5]]))

---
compute orthogonal vectors for pairs (1,2) (2,3) (3,1)

In [39]:
v12o = CrossNd((v1,v2))
v23o = CrossNd((v2,v3))
v31o = CrossNd((v3,v1))
v12o,v23o,v31o

(array([-1.8 , -0.45, 11.7 ]),
 array([ 9.92, -0.75,  0.12]),
 array([-2.3,  7.5, -1.2]))

---
check orthogonality

In [40]:
# v12o must be orthogonal to both v1 and v2
v12o @ v1, v12o @ v2

(0.0, -4.440892098500626e-16)

In [41]:
# v23o must be orthogonal to both v2 and v3
v23o @ v2, v23o @ v3

(4.2674197509029455e-16, 5.551115123125783e-17)

In [42]:
# v31o must be orthogonal to both v3 and v1
v31o @ v3, v31o @ v1

(8.881784197001252e-16, 3.1086244689504383e-15)

# Reciprocal Basis

*Basis vectors* $\mathbf{e}_{i}$ and $\mathbf{e}^{j}$ are reciprocal if $\mathbf{e}_{i}\cdot\mathbf{e}^{j}=\delta_{i\cdot}^{\cdot j}$ where $\delta_{i,j}$ is Kronecker delta function

**Q2: implement** `Reciprocal` **function to return reciprocal basis for a square matrix with basis vectors in columns or list of lists in square form**

In [43]:
def Reciprocal(V):
    """
    PRE:
        - V is square numpy.array or square list of lists
    POST:
        - function returns reciprocal basis vector
    """
    pass   


In [53]:
def Reciprocal(V):
    pass

In [54]:
v1 = numpy.array([1., 2.])
v2 = numpy.array([3., 1.])
V = numpy.stack([v1,v2])
v1,v2,V

(array([1., 2.]),
 array([3., 1.]),
 array([[1., 2.],
        [3., 1.]]))

In [55]:
VR = Reciprocal(V)
VR

array([[-0.2,  0.4],
       [ 0.6, -0.2]])

In [57]:
V @ VR

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])